{
 "title": "New dashboard",
 "time": { "from": "now-15s", "to": "now" },
 "refresh": "100ms",
 "templating": {
  "list": [
   {
    "name": "tankTempThresh",
    "label": "tankTempThresh",
    "query": {
     "query": "from(bucket: \"Test1\")\r\n  |> range(start: -5m)               // recent data\r\n  |> filter(fn: (r) => r._measurement == \"tankTempThresh\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> last()                            \r\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Configuration Name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test1\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"ConfigName\")\r\n  |> filter(fn: (r) => r._field == \"value_str\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "description": "Measured water brake power",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "HP" } },
   "targets": [
    {
     "query": "from(bucket: \"Test1\")\r\n  |> range(start: -5m)                       // last 5 minutes, adjust as needed\r\n  |> filter(fn: (r) => r._measurement == \"power\")\r\n  |> filter(fn: (r) => r._field == \"value\")   // numeric RPM field\r\n  |> aggregateWindow(every: 100ms, fn: mean)    // optional: smooth data\r\n  |> yield(name: \"RPM over time\")\r\n"
    }
   ]
  },
  {
   "title": "Gear Ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test1\")\r\n  |> range(start: -1h)                       // last hour of data\r\n  |> filter(fn: (r) => r._measurement == \"GearRatio\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false) // smooth data for sparkline\r\n"
    }
   ]
  },
  {
   "title": "Ambient Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test1\")\r\n  |> range(start: -5m)               // recent data\r\n  |> filter(fn: (r) => r._measurement == \"ambTemp\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> last()                            // take the latest value\r\n"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"Test1\")\r\n  |> range(start: -5m)                       // last 5 minutes, adjust as needed\r\n  |> filter(fn: (r) => r._measurement == \"dynoLoad\")\r\n  |> filter(fn: (r) => r._field == \"value\")   // numeric RPM field\r\n  |> aggregateWindow(every: 100ms, fn: mean)    // optional: smooth data\r\n  |> yield(name: \"lbf over time\")\r\n"
    }
   ]
  },
  {
   "title": "Tank Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test1\")\r\n  |> range(start: -5m)               // recent data\r\n  |> filter(fn: (r) => r._measurement == \"tankTemp\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> last()                            // take the latest value"
    }
   ]
  },
  {
   "title": "Outlet Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test1\")\r\n  |> range(start: -5m)               // recent data\r\n  |> filter(fn: (r) => r._measurement == \"outletTemp\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> last()                            // take the latest value"
    }
   ]
  },
  {
   "title": "RPMs",
   "type": "timeseries",
   "description": "RPM Time Series Data",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "from(bucket: \"Test1\")\r\n  |> range(start: -5m)                       // last 5 minutes, adjust as needed\r\n  |> filter(fn: (r) => r._measurement == \"wheelSpeed\")\r\n  |> filter(fn: (r) => r._field == \"value\")   // numeric RPM field\r\n  |> aggregateWindow(every: 100ms, fn: mean)    // optional: smooth data\r\n  |> yield(name: \"RPM over time\")\r\n"
    }
   ]
  },
  {
   "title": "Ambient Pressure",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test1\")\r\n  |> range(start: -5m)               // recent data\r\n  |> filter(fn: (r) => r._measurement == \"ambPressure\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> last()                            // take the latest value\r\n"
    }
   ]
  },
  {
   "title": "Ambient Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Test1\")\r\n  |> range(start: -5m)               // recent data\r\n  |> filter(fn: (r) => r._measurement == \"ambHumidity\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> last()                            // take the latest value\r\n"
    }
   ]
  },
  {
   "title": "Valve Position",
   "type": "timeseries",
   "description": "RPM Time Series Data",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Test1\")\r\n  |> range(start: -5m)                       // last 5 minutes, adjust as needed\r\n  |> filter(fn: (r) => r._measurement == \"valvePosition\")\r\n  |> filter(fn: (r) => r._field == \"value\")   // numeric RPM field\r\n  |> aggregateWindow(every: 100ms, fn: mean)    // optional: smooth data\r\n  |> yield(name: \"RPM over time\")\r\n"
    }
   ]
  }
 ]
}