{
 "title": "Run Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "tankTempThresh",
    "label": "tankTempThresh",
    "query": {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -5m)               // recent data\r\n  |> filter(fn: (r) => r._measurement == \"tankTempThresh\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> last()                            \r\n"
    }
   },
   { "name": "Bucket", "label": "Bucket Name", "query": "whatever" },
   {
    "name": "runName",
    "label": "Select Run",
    "query": {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"runData\")\r\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last Run Name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"runData\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Power vs RPM",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -60m)                       // last 5 minutes, adjust as needed\r\n  |> filter(fn: (r) => r._measurement == \"power\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.runName == \"${runName}\")  // numeric RPM field\r\n  |> set(key: \"_field\", value: \"power\")"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -60m)                       // last 5 minutes, adjust as needed\r\n  |> filter(fn: (r) => r._measurement == \"engineSpeed\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.runName == \"${runName}\")// numeric RPM field\r\n  |> set(key: \"_field\", value: \"rpm\")"
    }
   ]
  },
  {
   "title": "Valve Position",
   "type": "timeseries",
   "description": "RPM Time Series Data",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -5m)                       // last 5 minutes, adjust as needed\r\n  |> filter(fn: (r) => r._measurement == \"valvePosition\")\r\n  |> filter(fn: (r) => r._field == \"value\")   // numeric RPM field\r\n  |> aggregateWindow(every: 100ms, fn: mean)    // optional: smooth data\r\n  |> yield(name: \"RPM over time\")\r\n"
    }
   ]
  },
  {
   "title": "Torque vs RPM",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -60m)                       // last 5 minutes, adjust as needed\r\n  |> filter(fn: (r) => r._measurement == \"engineTorque\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.runName == \"${runName}\")  // numeric RPM field\r\n  |> set(key: \"_field\", value: \"torque\")"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -60m)                       // last 5 minutes, adjust as needed\r\n  |> filter(fn: (r) => r._measurement == \"engineSpeed\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.runName == \"${runName}\")// numeric RPM field\r\n  |> set(key: \"_field\", value: \"rpm\")"
    }
   ]
  },
  {
   "title": "RPMs",
   "type": "timeseries",
   "description": "RPM Time Series Data",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -10m)                       // last 5 minutes, adjust as needed\r\n  |> filter(fn: (r) => r._measurement == \"engineSpeed\")\r\n  |> filter(fn: (r) => r._field == \"value\")   // numeric RPM field\r\n  |> aggregateWindow(every: 200ms, fn: last)    // optional: smooth data\r\n  |> yield(name: \"RPM over time\")\r\n"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -10m)                       // last 5 minutes, adjust as needed\r\n  |> filter(fn: (r) => r._measurement == \"dynoLoad\")\r\n  |> filter(fn: (r) => r._field == \"value\")   // numeric RPM field\r\n  |> aggregateWindow(every: 200ms, fn: mean)    // optional: smooth data\r\n  |> yield(name: \"lbf over time\")\r\n"
    }
   ]
  },
  {
   "title": "Gear Ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -1h)                       // last hour of data\r\n  |> filter(fn: (r) => r._measurement == \"GearRatio\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false) // smooth data for sparkline\r\n"
    }
   ]
  },
  {
   "title": "Ambient Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -5m)               // recent data\r\n  |> filter(fn: (r) => r._measurement == \"ambTemp\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> last()                            // take the latest value\r\n"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "description": "Measured water brake power",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "HP" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -10m)                       // last 5 minutes, adjust as needed\r\n  |> filter(fn: (r) => r._measurement == \"power\")\r\n  |> filter(fn: (r) => r._field == \"value\")   // numeric RPM field\r\n  |> aggregateWindow(every: 200ms, fn: mean)    // optional: smooth data\r\n  |> yield(name: \"RPM over time\")\r\n"
    }
   ]
  },
  {
   "title": "Tank Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -5m)               // recent data\r\n  |> filter(fn: (r) => r._measurement == \"tankTemp\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> last()                            // take the latest value"
    }
   ]
  },
  {
   "title": "Outlet Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -5m)               // recent data\r\n  |> filter(fn: (r) => r._measurement == \"outletTemp\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> last()                            // take the latest value"
    }
   ]
  }
 ]
}